package binance

import (
	"net/http"
	"net/http/httptest"
	"os"
	"reflect"
	"sync/atomic"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/thrasher-corp/gocryptotrader/encoding/json"
	exchange "github.com/thrasher-corp/gocryptotrader/exchanges"
	"github.com/thrasher-corp/gocryptotrader/exchanges/request"
	testexch "github.com/thrasher-corp/gocryptotrader/internal/testing/exchange"
	"github.com/thrasher-corp/gocryptotrader/types"
)

type documentedResponse struct {
	Source string          `json:"source"`
	Method string          `json:"method"`
	Path   string          `json:"path"`
	Data   json.RawMessage `json:"data"`
}

// TestDocumentedResponseModels checks the transport and every documented response
// member against Binance's official examples. Endpoint parameter builders are
// exercised separately; these fixtures do not establish live account compatibility.
func TestDocumentedResponseModels(t *testing.T) {
	data, err := os.ReadFile("testdata/documented_responses.json")
	require.NoError(t, err, "documented responses must load")
	var fixtures map[string]*documentedResponse
	require.NoError(t, json.Unmarshal(data, &fixtures), "documented responses must decode")
	var current atomic.Pointer[documentedResponse]
	server := httptest.NewTestServer(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fixture := current.Load()
		assert.Equal(t, fixture.Path, r.URL.Path, "request path should select its documented endpoint")
		assert.Equal(t, fixture.Method, r.Method, "request method should match its documentation")
		w.Header().Set("Content-Type", "application/json")
		_, err := w.Write(fixture.Data)
		assert.NoError(t, err, "mock response should be written")
	}))
	local := new(Exchange)
	require.NoError(t, testexch.Setup(local), "test exchange must initialise")
	local.SkipAuthCheck = true
	require.NoError(t, local.SetHTTPClient(server.Client()), "test HTTP client must initialise")
	require.NoError(t, local.API.Endpoints.SetRunningURL(exchange.RestSpot.String(), server.URL), "HTTP URL must be the mock server")
	for _, tc := range []struct {
		fixture, name string
		response      any
	}{
		{"algo/cancel_algo_order_future_algo", "CancelFuturesAlgoOrder", new(*AlgoOrderResponse)},
		{"algo/query_current_algo_open_orders_future_algo", "GetFuturesCurrentAlgoOpenOrders", new(*AlgoOrders)},
		{"algo/query_historical_algo_orders_future_algo", "GetFuturesHistoricalAlgoOrders", new(*AlgoOrders)},
		{"algo/query_sub_orders_future_algo", "GetFuturesSubOrders", new(*AlgoSubOrders)},
		{"algo/time_weighted_average_price_future_algo", "FuturesTWAPOrder", new(*AlgoOrderResponse)},
		{"algo/volume_participation_future_algo", "VolumeParticipationNewOrder", new(*AlgoOrderResponse)},
		{"algo/cancel_algo_order_spot_algo", "CancelSpotAlgoOrder", new(*AlgoOrderResponse)},
		{"algo/query_current_algo_open_orders_spot_algo", "GetCurrentSpotAlgoOpenOrder", new(*AlgoOrders)},
		{"algo/query_historical_algo_orders_spot_algo", "GetSpotHistoricalAlgoOrders", new(*AlgoOrders)},
		{"algo/query_sub_orders_spot_algo", "GetSpotSubOrders", new(*AlgoSubOrders)},
		{"algo/time_weighted_average_price_spot_algo", "SpotTWAPNewOrder", new(*AlgoOrderResponse)},
		{"c2c/get_c2_c_trade_history", "GetC2CTradeHistory", new(*C2CTransaction)},
		{"convert/list_all_convert_pairs", "GetAllConvertPairs", new([]*ConvertPairInfo)},
		{"convert/query_order_quantity_precision_per_asset", "GetOrderQuantityPrecisionPerAsset", new([]*OrderQuantityPrecision)},
		{"convert/accept_quote", "AcceptQuote", new(*QuoteOrderStatus)},
		{"convert/cancel_limit_order", "CancelLimitOrder", new(*OrderStatusResponse)},
		{"convert/get_convert_trade_history", "GetConvertTradeHistory", new(*ConvertTradeHistory)},
		{"convert/order_status", "GetConvertOrderStatus", new(*ConvertOrderStatus)},
		{"convert/place_limit_order", "PlaceLimitOrder", new(*OrderStatusResponse)},
		{"convert/query_limit_open_orders", "GetLimitOpenOrders", new(*LimitOrderHistory)},
		{"convert/send_quote_request", "SendQuoteRequest", new(*ConvertQuoteResponse)},
		{"copy_trading/get_futures_lead_trader_status", "GetFuturesLeadTraderStatus", new(*LeadTraderStatusResponse)},
		{"copy_trading/get_futures_lead_trading_symbol_whitelist", "GetFuturesLeadTradingSymbolWhitelist", new(*LeadTradingSymbolsResponse)},
		{"crypto_loan/check_collateral_repay_rate", "CheckCollateralRepayRate", new(*CollateralRepayRate)},
		{"crypto_loan/flexible_loan_adjust_ltv", "FlexibleLoanAdjustLTV", new(*FlexibleLoanAdjustLTV)},
		{"crypto_loan/flexible_loan_borrow", "FlexibleLoanBorrow", new(*FlexibleLoanBorrow)},
		{"crypto_loan/flexible_loan_repay", "FlexibleLoanRepay", new(*FlexibleLoanRepay)},
		{"crypto_loan/get_flexible_loan_assets_data", "FlexibleLoanAssetsData", new(*FlexibleLoanAssetsData)},
		{"crypto_loan/get_flexible_loan_borrow_history", "FlexibleLoanBorrowHistory", new(*FlexibleLoanBorrowHistory)},
		{"crypto_loan/get_flexible_loan_collateral_assets_data", "FlexibleCollateralAssetsData", new(*FlexibleCollateralAssetsData)},
		{"crypto_loan/get_flexible_loan_interest_rate_history", "GetFlexibleLoanInterestRateHistory", new(*FlexibleLoanInterestRateHistory)},
		{"crypto_loan/get_flexible_loan_liquidation_history", "GetFlexibleLoanLiquidiationHistory", new(*FlexibleLoanLiquidiationhistory)},
		{"crypto_loan/get_flexible_loan_ltv_adjustment_history", "FlexibleLoanLTVAdjustmentHistory", new(*FlexibleLoanLTVAdjustmentHistory)},
		{"crypto_loan/get_flexible_loan_ongoing_orders", "FlexibleLoanOngoingOrders", new(*FlexibleLoanOngoingOrder)},
		{"crypto_loan/get_flexible_loan_repayment_history", "FlexibleLoanRepayHistory", new(*FlexibleLoanRepayHistory)},
		{"crypto_loan/get_crypto_loans_income_history", "CryptoLoanIncomeHistory", new([]*CryptoLoansIncomeHistory)},
		{"crypto_loan/get_loan_borrow_history", "CryptoLoanBorrowHistory", new(*LoanBorrowHistory)},
		{"crypto_loan/get_loan_ltv_adjustment_history", "CryptoLoanLTVAdjustmentHistory", new(*CryptoLoanLTVAdjustmentHistory)},
		{"crypto_loan/get_loan_repayment_history", "CryptoLoanRepaymentHistory", new(*CryptoLoanRepayHistory)},
		{"derivatives_trading_coin_futures/account_information", "GetFuturesAccountInfo", new(*FuturesAccountInformation)},
		{"derivatives_trading_coin_futures/futures_account_balance", "GetFuturesAccountBalance", new([]*FuturesAccountBalanceData)},
		{"derivatives_trading_coin_futures/get_current_position_mode", "GetCFuturesPositionSideDual", new(*CFuturesPositionSideDual)},
		{"derivatives_trading_coin_futures/get_download_id_for_futures_order_history", "GetCFuturesOrderHistoryDownloadID", new(*UTransactionDownloadID)},
		{"derivatives_trading_coin_futures/get_download_id_for_futures_trade_history", "GetCFuturesTradeHistoryDownloadID", new(*UTransactionDownloadID)},
		{"derivatives_trading_coin_futures/get_download_id_for_futures_transaction_history", "GetCFuturesTransactionHistoryDownloadID", new(*UTransactionDownloadID)},
		{"derivatives_trading_coin_futures/get_futures_order_history_download_link_by_id", "GetCFuturesOrderHistoryDownloadLink", new(*UTransactionHistoryDownloadLink)},
		{"derivatives_trading_coin_futures/get_futures_trade_download_link_by_id", "GetCFuturesTradeHistoryDownloadLink", new(*UTransactionHistoryDownloadLink)},
		{"derivatives_trading_coin_futures/get_futures_transaction_history_download_link_by_id", "GetCFuturesTransactionHistoryDownloadLink", new(*UTransactionHistoryDownloadLink)},
		{"derivatives_trading_coin_futures/get_income_history", "FuturesIncomeHistory", new([]*FuturesIncomeHistoryData)},
		{"derivatives_trading_coin_futures/notional_bracket_for_symbol", "GetCFuturesLeverageBracket", new([]*CFuturesLeverageBracketV2)},
		{"derivatives_trading_coin_futures/user_commission_rate", "GetCFuturesCommissionRate", new(*CFuturesCommissionRate)},
		{"derivatives_trading_coin_futures/basis", "GetFuturesBasisData", new([]*FuturesBasisData)},
		{"derivatives_trading_coin_futures/check_server_time", "CFuturesServerTime", new(struct {
			ServerTime types.Time `json:"serverTime"`
		})},
		{"derivatives_trading_coin_futures/compressed_aggregate_trades_list", "GetFuturesAggregatedTradesList", new([]*AggregatedTrade)},
		{"derivatives_trading_coin_futures/continuous_contract_kline_candlestick_data", "GetContinuousKlineData", new([]*CFuturesCandleStick)},
		{"derivatives_trading_coin_futures/exchange_information", "FuturesExchangeInfo", new(*CExchangeInfo)},
		{"derivatives_trading_coin_futures/get_funding_rate_history_of_perpetual_futures", "FuturesGetFundingHistory", new([]*FundingRateHistory)},
		{"derivatives_trading_coin_futures/get_funding_rate_info", "GetFundingRateInfo", new([]*FundingRateInfoResponse)},
		{"derivatives_trading_coin_futures/index_price_and_mark_price", "GetIndexAndMarkPrice", new([]*IndexMarkPrice)},
		{"derivatives_trading_coin_futures/index_price_kline_candlestick_data", "GetIndexPriceKlines", new([]*CFuturesCandleStick)},
		{"derivatives_trading_coin_futures/kline_candlestick_data", "GetFuturesKlineData", new([]*CFuturesCandleStick)},
		{"derivatives_trading_coin_futures/long_short_ratio", "GetMarketRatio", new([]*TopTraderAccountRatio)},
		{"derivatives_trading_coin_futures/mark_price_kline_candlestick_data", "GetMarkPriceKline", new([]*CFuturesCandleStick)},
		{"derivatives_trading_coin_futures/old_trades_lookup", "GetFuturesHistoricalTrades", new([]*UPublicTradesData)},
		{"derivatives_trading_coin_futures/open_interest", "GetCFuturesOpenInterest", new(*CFuturesOpenInterest)},
		{"derivatives_trading_coin_futures/open_interest", "OpenInterest", new(*OpenInterestData)},
		{"derivatives_trading_coin_futures/open_interest_statistics", "GetOpenInterestStats", new([]*OpenInterestStats)},
		{"derivatives_trading_coin_futures/order_book", "GetFuturesOrderbook", new(*OrderBook)},
		{"derivatives_trading_coin_futures/premium_index_kline_data", "GetPremiumIndexKlineData", new([]*CFuturesCandleStick)},
		{"derivatives_trading_coin_futures/query_index_price_constituents", "GetCFuturesIndexPriceConstituents", new(*CFuturesIndexPriceConstituents)},
		{"derivatives_trading_coin_futures/recent_trades_list", "GetFuturesPublicTrades", new([]*FuturesPublicTradesData)},
		{"derivatives_trading_coin_futures/symbol_order_book_ticker", "GetFuturesOrderbookTicker", new([]*SymbolOrderBookTicker)},
		{"derivatives_trading_coin_futures/symbol_price_ticker", "GetFuturesSymbolPriceTicker", new([]*SymbolPriceTicker)},
		{"derivatives_trading_coin_futures/taker_buy_sell_volume", "GetFuturesTakerVolume", new([]*TakerBuySellVolume)},
		{"derivatives_trading_coin_futures/ticker24hr_price_change_statistics", "GetFuturesSwapTickerChangeStats", new([]*PriceChangeStats)},
		{"derivatives_trading_coin_futures/top_trader_long_short_ratio_accounts", "GetTraderFuturesAccountRatio", new([]*TopTraderAccountRatio)},
		{"derivatives_trading_coin_futures/top_trader_long_short_ratio_positions", "GetTraderFuturesPositionsRatio", new([]*TopTraderPositionRatio)},
		{"derivatives_trading_coin_futures/account_trade_list", "FuturesTradeHistory", new([]*FuturesAccountTradeList)},
		{"derivatives_trading_coin_futures/all_orders", "GetAllFuturesOrders", new([]*FuturesOrderData)},
		{"derivatives_trading_coin_futures/auto_cancel_all_open_orders", "AutoCancelAllOpenOrders", new(*AutoCancelAllOrdersData)},
		{"derivatives_trading_coin_futures/cancel_all_open_orders", "FuturesCancelAllOpenOrders", new(*GenericAuthResponse)},
		{"derivatives_trading_coin_futures/cancel_multiple_orders", "FuturesBatchCancelOrders", new([]*BatchCancelOrderData)},
		{"derivatives_trading_coin_futures/cancel_order", "FuturesCancelOrder", new(*FuturesOrderGetData)},
		{"derivatives_trading_coin_futures/change_initial_leverage", "FuturesChangeInitialLeverage", new(*FuturesLeverageData)},
		{"derivatives_trading_coin_futures/change_margin_type", "FuturesChangeMarginType", new(*GenericAuthResponse)},
		{"derivatives_trading_coin_futures/change_position_mode", "ChangeCFuturesPositionMode", new(*SuccessResponse)},
		{"derivatives_trading_coin_futures/current_all_open_orders", "GetFuturesAllOpenOrders", new([]*FuturesOrderData)},
		{"derivatives_trading_coin_futures/get_order_modify_history", "GetCFuturesOrderModifyHistory", new([]*USDTAmendInfo)},
		{"derivatives_trading_coin_futures/get_position_margin_change_history", "FuturesMarginChangeHistory", new([]*GetPositionMarginChangeHistoryData)},
		{"derivatives_trading_coin_futures/modify_isolated_position_margin", "ModifyIsolatedPositionMargin", new(*FuturesMarginUpdatedResponse)},
		{"derivatives_trading_coin_futures/modify_multiple_orders", "ModifyCFuturesOrders", new([]*FuturesOrderData)},
		{"derivatives_trading_coin_futures/modify_order", "ModifyCFuturesOrder", new(*FuturesOrderData)},
		{"derivatives_trading_coin_futures/new_order", "FuturesNewOrder", new(*FuturesOrderPlaceData)},
		{"derivatives_trading_coin_futures/place_multiple_orders", "FuturesBatchOrder", new([]*FuturesOrderPlaceData)},
		{"derivatives_trading_coin_futures/position_adl_quantile_estimation", "FuturesPositionsADLEstimate", new([]*ADLEstimateData)},
		{"derivatives_trading_coin_futures/position_information", "FuturesPositionsInfo", new([]*FuturesPositionInformation)},
		{"derivatives_trading_coin_futures/query_current_open_order", "FuturesOpenOrderData", new(*FuturesOrderGetData)},
		{"derivatives_trading_coin_futures/query_order", "FuturesGetOrderData", new(*FuturesOrderGetData)},
		{"derivatives_trading_coin_futures/users_force_orders", "FuturesForceOrders", new([]*ForcedOrdersData)},
		{"derivatives_trading_coin_futures/keepalive_user_data_stream", "KeepCFuturesListenKeyAlive", new(*ListenKeyResponse)},
		{"derivatives_trading_coin_futures/start_user_data_stream", "CreateCFuturesListenKey", new(*ListenKeyResponse)},
		{"derivatives_trading_options/account_funding_flow", "GetAccountFundingFlow", new([]*AccountFunding)},
		{"derivatives_trading_options/option_margin_account_information", "GetOptionMarginAccountInformation", new(*OptionMarginAccountInfo)},
		{"derivatives_trading_options/check_server_time", "CheckEOptionsServerTime", new(struct {
			ServerTime types.Time `json:"serverTime"`
		})},
		{"derivatives_trading_options/exchange_information", "GetOptionsExchangeInformation", new(*EOptionExchangeInfo)},
		{"derivatives_trading_options/historical_exercise_records", "GetEOptionsHistoricalExerciseRecords", new([]*ExerciseHistoryItem)},
		{"derivatives_trading_options/index_price", "GetEOptionsSymbolPriceTicker", new(*EOptionIndexSymbolPriceTicker)},
		{"derivatives_trading_options/kline_candlestick_data", "GetEOptionsCandlesticks", new([]*EOptionsCandlestick)},
		{"derivatives_trading_options/open_interest", "GetEOptionsOpenInterests", new([]*OpenInterest)},
		{"derivatives_trading_options/option_mark_price", "GetOptionMarkPrice", new([]*OptionMarkPrice)},
		{"derivatives_trading_options/order_book", "GetEOptionsOrderbook", new(*EOptionsOrderbook)},
		{"derivatives_trading_options/recent_block_trades_list", "GetEOptionsRecentBlockTrades", new([]*EOptionsBlockTrade)},
		{"derivatives_trading_options/recent_trades_list", "GetEOptionsRecentTrades", new([]*EOptionsTradeItem)},
		{"derivatives_trading_options/ticker24hr_price_change_statistics", "GetEOptions24hrTickerPriceChangeStatistics", new([]*EOptionTicker)},
		{"derivatives_trading_options/accept_block_trade_order", "AcceptEOptionsBlockTradeOrder", new(*EOptionsBlockTradeOrder)},
		{"derivatives_trading_options/account_block_trade_list", "GetEOptionsBlockUserTrades", new([]*EOptionsAccountBlockTrade)},
		{"derivatives_trading_options/extend_block_trade_order", "ExtendEOptionsBlockTradeOrder", new(*EOptionsBlockTradeOrder)},
		{"derivatives_trading_options/new_block_trade_order", "NewEOptionsBlockTradeOrder", new(*EOptionsBlockTradeOrder)},
		{"derivatives_trading_options/query_block_trade_details", "GetEOptionsBlockTradeDetail", new(*EOptionsBlockTradeOrder)},
		{"derivatives_trading_options/query_block_trade_order", "GetEOptionsBlockTradeOrders", new([]*EOptionsBlockTradeOrder)},
		{"derivatives_trading_options/auto_cancel_all_open_orders", "GetOptionsAutoCancelAllOpenOrdersHeartbeat", new(struct {
			Underlyings []*string `json:"underlyings"`
		})},
		{"derivatives_trading_options/get_auto_cancel_all_open_orders", "GetAutoCancelAllOpenOrdersConfig", new(*UnderlyingCountdown)},
		{"derivatives_trading_options/get_market_maker_protection_config", "GetOptionsMarketMakerProtection", new(*MarketMakerProtection)},
		{"derivatives_trading_options/reset_market_maker_protection_config", "ResetMarketMaketProtection", new(*MarketMakerProtection)},
		{"derivatives_trading_options/set_auto_cancel_all_open_orders", "SetOptionsAutoCancelAllOpenOrders", new(*UnderlyingCountdown)},
		{"derivatives_trading_options/set_market_maker_protection_config", "SetOptionsMarketMakerProtectionConfig", new(*MarketMakerProtection)},
		{"derivatives_trading_options/account_trade_list", "GetEOptionsAccountTradeList", new([]*OptionsAccountTradeItem)},
		{"derivatives_trading_options/cancel_all_option_orders_by_underlying", "CancelAllOptionsOrdersByUnderlying", new(*SuccessResponse)},
		{"derivatives_trading_options/cancel_multiple_option_orders", "CancelBatchOptionsOrders", new([]*OptionOrder)},
		{"derivatives_trading_options/cancel_option_order", "CancelOptionsOrder", new(*OptionOrder)},
		{"derivatives_trading_options/new_order", "NewOptionsOrder", new(*OptionOrder)},
		{"derivatives_trading_options/option_position_information", "GetOptionPositionInformation", new([]*OptionPosition)},
		{"derivatives_trading_options/place_multiple_orders", "PlaceBatchEOptionsOrder", new([]*OptionOrder)},
		{"derivatives_trading_options/query_current_open_option_orders", "GetCurrentOpenOptionsOrders", new([]*OptionOrder)},
		{"derivatives_trading_options/query_option_order_history", "GetOptionsOrdersHistory", new([]*OptionOrder)},
		{"derivatives_trading_options/query_single_order", "GetSingleEOptionsOrder", new(*OptionOrder)},
		{"derivatives_trading_options/user_commission", "GetEOptionsUserCommission", new(*EOptionsUserCommission)},
		{"derivatives_trading_options/user_exercise_record", "GetUserOptionsExerciseRecord", new([]*UserOptionsExerciseRecord)},
		{"derivatives_trading_options/start_user_data_stream", "CreateOptionsListenKey", new(*ListenKeyResponse)},
		{"derivatives_trading_portfolio_margin/account_balance", "GetAccountBalance", new(AccountBalanceResponse)},
		{"derivatives_trading_portfolio_margin/account_information", "GetPortfolioMarginAccountInformation", new(*AccountInformation)},
		{"derivatives_trading_portfolio_margin/bnb_transfer", "BNBTransfer", new(struct {
			TransactionID int64 `json:"tranId"`
		})},
		{"derivatives_trading_portfolio_margin/change_auto_repay_futures_status", "ChangeAutoRepayFuturesStatus", new(struct {
			Message string `json:"msg"`
		})},
		{"derivatives_trading_portfolio_margin/change_cm_initial_leverage", "ChangeCMInitialLeverage", new(*CMInitialLeverage)},
		{"derivatives_trading_portfolio_margin/change_cm_position_mode", "ChangeCMPositionMode", new(*SuccessResponse)},
		{"derivatives_trading_portfolio_margin/change_um_initial_leverage", "ChangeUMInitialLeverage", new(*InitialLeverage)},
		{"derivatives_trading_portfolio_margin/change_um_position_mode", "ChangeUMPositionMode", new(*SuccessResponse)},
		{"derivatives_trading_portfolio_margin/cm_notional_and_leverage_brackets", "GetCMNotionalAndLeverageBrackets", new([]*CMNotionalAndLeverage)},
		{"derivatives_trading_portfolio_margin/fund_auto_collection", "FundAutoCollection", new(struct {
			Message string `json:"msg"`
		})},
		{"derivatives_trading_portfolio_margin/fund_collection_by_asset", "FundCollectionByAsset", new(struct {
			Message string `json:"msg"`
		})},
		{"derivatives_trading_portfolio_margin/get_auto_repay_futures_status", "GetAutoRepayFuturesStatus", new(*AutoRepayStatus)},
		{"derivatives_trading_portfolio_margin/get_cm_account_detail", "GetCMAccountDetail", new(*AccountDetail)},
		{"derivatives_trading_portfolio_margin/get_cm_current_position_mode", "GetCMCurrentPositionMode", new(*DualPositionMode)},
		{"derivatives_trading_portfolio_margin/get_cm_income_history", "GetCMIncomeHistory", new([]*IncomeItem)},
		{"derivatives_trading_portfolio_margin/get_download_id_for_um_futures_order_history", "GetUMOrderHistoryDownloadID", new(*UTransactionDownloadID)},
		{"derivatives_trading_portfolio_margin/get_download_id_for_um_futures_trade_history", "GetUMTradeHistoryDownloadID", new(*UTransactionDownloadID)},
		{"derivatives_trading_portfolio_margin/get_download_id_for_um_futures_transaction_history", "GetUMTransactionHistoryDownloadID", new(*UTransactionDownloadID)},
		{"derivatives_trading_portfolio_margin/get_margin_borrow_loan_interest_history", "GetMarginBorrowOrLoanInterestHistory", new(*MarginBorrowOrLoanInterest)},
		{"derivatives_trading_portfolio_margin/get_um_account_detail_v2", "GetUMAccountDetail", new(*UMAccountDetailV2)},
		{"derivatives_trading_portfolio_margin/get_um_current_position_mode", "GetUMAccountPositionMode", new(*DualPositionMode)},
		{"derivatives_trading_portfolio_margin/get_um_futures_order_download_link_by_id", "GetUMOrderHistoryDownloadLink", new(*UTransactionHistoryDownloadLink)},
		{"derivatives_trading_portfolio_margin/get_um_futures_trade_download_link_by_id", "GetUMTradeHistoryDownloadLink", new(*UTransactionHistoryDownloadLink)},
		{"derivatives_trading_portfolio_margin/get_um_futures_transaction_download_link_by_id", "GetUMTransactionHistoryDownloadLink", new(*UTransactionHistoryDownloadLink)},
		{"derivatives_trading_portfolio_margin/get_um_income_history", "GetUMIncomeHistory", new([]*IncomeItem)},
		{"derivatives_trading_portfolio_margin/get_user_commission_rate_for_cm", "GetCMUserCommissionRate", new(*CommissionRate)},
		{"derivatives_trading_portfolio_margin/get_user_commission_rate_for_um", "GetUMUserCommissionRate", new(*CommissionRate)},
		{"derivatives_trading_portfolio_margin/margin_max_borrow", "GetPMMarginMaxBorrow", new(*MaxBorrow)},
		{"derivatives_trading_portfolio_margin/portfolio_margin_um_trading_quantitative_rules_indicators", "GetPortfolioMarginUMTradingQuantitativeRulesIndicator", new(*TradingQuantitativeRulesIndicators)},
		{"derivatives_trading_portfolio_margin/query_cm_position_information", "GetCMPositionInformation", new([]*CMPositionInformation)},
		{"derivatives_trading_portfolio_margin/query_margin_loan_record", "GetMarginLoanRecord", new(*MarginLoanRecord)},
		{"derivatives_trading_portfolio_margin/query_margin_max_withdraw", "GetMarginMaxWithdrawal", new(struct {
			Amount types.Number `json:"amount"`
		})},
		{"derivatives_trading_portfolio_margin/query_margin_repay_record", "GetMarginRepayRecord", new(*MarginRepayRecord)},
		{"derivatives_trading_portfolio_margin/query_portfolio_margin_negative_balance_interest_history", "GetPortfolioMarginNegativeBalanceInterestHistory", new([]*PortfolioMarginNegativeBalanceInterest)},
		{"derivatives_trading_portfolio_margin/query_um_position_information", "GetUMPositionInformation", new([]*UMPositionInformation)},
		{"derivatives_trading_portfolio_margin/query_user_negative_balance_auto_exchange_record", "GetUserNegativeBalanceAutoExchangeRecord", new(*UserNegativeBalanceRecord)},
		{"derivatives_trading_portfolio_margin/query_user_rate_limit", "GetUserRateLimits", new([]*RateLimitInfo)},
		{"derivatives_trading_portfolio_margin/repay_futures_negative_balance", "RepayFuturesNegativeBalance", new(struct {
			Message string `json:"msg"`
		})},
		{"derivatives_trading_portfolio_margin/um_futures_account_configuration", "GetUMFuturesAccountConfig", new(*UMFuturesAccountConfig)},
		{"derivatives_trading_portfolio_margin/um_futures_symbol_configuration", "GetUMFuturesSymbolConfig", new([]*UMFuturesSymbolConfig)},
		{"derivatives_trading_portfolio_margin/um_notional_and_leverage_brackets", "GetUMNotionalAndLeverageBrackets", new([]*NotionalAndLeverage)},
		{"derivatives_trading_portfolio_margin/cancel_all_cm_open_conditional_orders", "CancelAllCMOpenConditionalOrders", new(*SuccessResponse)},
		{"derivatives_trading_portfolio_margin/cancel_all_cm_open_orders", "CancelAllCMOrders", new(*SuccessResponse)},
		{"derivatives_trading_portfolio_margin/cancel_all_um_algo_open_orders", "CancelAllUMAlgoOpenOrders", new(*SuccessResponse)},
		{"derivatives_trading_portfolio_margin/cancel_all_um_open_orders", "CancelAllUMOrders", new(*SuccessResponse)},
		{"derivatives_trading_portfolio_margin/cancel_cm_conditional_order", "CancelCMConditionalOrder", new(*ConditionalOrder)},
		{"derivatives_trading_portfolio_margin/cancel_cm_order", "CancelCMOrder", new(*UMCMOrder)},
		{"derivatives_trading_portfolio_margin/cancel_margin_account_all_open_orders_on_a_symbol", "CancelAllMarginOpenOrdersBySymbol", new(MarginAccOrdersList)},
		{"derivatives_trading_portfolio_margin/cancel_margin_account_oco_orders", "CancelMarginAccountOCOOrders", new(*OCOOrder)},
		{"derivatives_trading_portfolio_margin/cancel_margin_account_order", "PMCancelMarginAccountOrder", new(*PortfolioMarginOrderResponse)},
		{"derivatives_trading_portfolio_margin/cancel_um_algo_order", "CancelUMAlgoOrder", new(*UMAlgoOrder)},
		{"derivatives_trading_portfolio_margin/cancel_um_order", "CancelUMOrder", new(*UMCMOrder)},
		{"derivatives_trading_portfolio_margin/cm_account_trade_list", "GetCMAccountTradeList", new([]*UMCMAccountTradeItem)},
		{"derivatives_trading_portfolio_margin/cm_position_adl_quantile_estimation", "GetCMPositionADLQuantileEstimation", new([]*ADLQuantileEstimation)},
		{"derivatives_trading_portfolio_margin/get_um_futures_bnb_burn_status", "GetUMFeeBurnStatus", new(*UFuturesFeeBurnStatus)},
		{"derivatives_trading_portfolio_margin/margin_account_borrow", "MarginAccountBorrow", new(struct {
			TransactionID types.PreciseNumber `json:"tranId"`
		})},
		{"derivatives_trading_portfolio_margin/margin_account_new_oco", "MarginAccountNewOCO", new(*OCOOrder)},
		{"derivatives_trading_portfolio_margin/margin_account_repay", "MarginAccountRepay", new(struct {
			TransactionID types.PreciseNumber `json:"tranId"`
		})},
		{"derivatives_trading_portfolio_margin/margin_account_repay_debt", "RepayMarginDebt", new(*MarginRepayDebtResponse)},
		{"derivatives_trading_portfolio_margin/margin_account_trade_list", "GetPMMarginAccountTradeList", new([]*TradeHistory)},
		{"derivatives_trading_portfolio_margin/modify_cm_order", "ModifyPMCMOrder", new(*UMCMOrder)},
		{"derivatives_trading_portfolio_margin/modify_um_order", "ModifyPMUMOrder", new(*UMCMOrder)},
		{"derivatives_trading_portfolio_margin/new_cm_conditional_order", "NewCMConditionalOrder", new(*ConditionalOrder)},
		{"derivatives_trading_portfolio_margin/new_cm_order", "NewCMOrder", new(*UMCMOrder)},
		{"derivatives_trading_portfolio_margin/new_margin_order", "NewMarginOrder", new(*PortfolioMarginOrderResponse)},
		{"derivatives_trading_portfolio_margin/new_um_algo_order", "NewUMAlgoOrder", new(*UMAlgoOrder)},
		{"derivatives_trading_portfolio_margin/new_um_order", "NewUMOrder", new(*UMCMOrder)},
		{"derivatives_trading_portfolio_margin/query_all_cm_conditional_orders", "GetAllCMConditionalOrders", new([]*ConditionalOrder)},
		{"derivatives_trading_portfolio_margin/query_all_cm_orders", "GetAllCMOrders", new([]*UMCMOrder)},
		{"derivatives_trading_portfolio_margin/query_all_current_cm_open_conditional_orders", "GetAllCMOpenConditionalOrders", new([]*ConditionalOrder)},
		{"derivatives_trading_portfolio_margin/query_all_current_cm_open_orders", "GetAllCMOpenOrders", new([]*UMCMOrder)},
		{"derivatives_trading_portfolio_margin/query_all_current_um_open_algo_orders", "GetAllUMOpenAlgoOrders", new([]*UMAlgoOrder)},
		{"derivatives_trading_portfolio_margin/query_all_current_um_open_orders", "GetAllUMOpenOrders", new([]*UMCMOrder)},
		{"derivatives_trading_portfolio_margin/query_all_margin_account_orders", "GetAllMarginAccountOrders", new([]*MarginOrder)},
		{"derivatives_trading_portfolio_margin/query_all_um_orders", "GetAllUMOrders", new([]*UMCMOrder)},
		{"derivatives_trading_portfolio_margin/query_cm_conditional_order_history", "GetAllCMConditionalOrderHistory", new(*ConditionalOrder)},
		{"derivatives_trading_portfolio_margin/query_cm_modify_order_history", "GetCMOrderModifyHistory", new([]*USDTAmendInfo)},
		{"derivatives_trading_portfolio_margin/query_cm_order", "GetCMOrder", new(*UMCMOrder)},
		{"derivatives_trading_portfolio_margin/query_current_cm_open_conditional_order", "GetCMConditionalOpenOrder", new(*ConditionalOrder)},
		{"derivatives_trading_portfolio_margin/query_current_cm_open_order", "GetCMOpenOrder", new([]*UMCMOrder)},
		{"derivatives_trading_portfolio_margin/query_current_margin_open_order", "GetCurrentMarginOpenOrders", new([]*MarginOrder)},
		{"derivatives_trading_portfolio_margin/query_current_um_open_algo_order", "GetUMOpenAlgoOrder", new(*UMAlgoOrder)},
		{"derivatives_trading_portfolio_margin/query_current_um_open_order", "GetUMOpenOrder", new(*UMCMOrder)},
		{"derivatives_trading_portfolio_margin/query_margin_account_order", "GetMarginAccountOrder", new(*MarginOrder)},
		{"derivatives_trading_portfolio_margin/query_margin_accounts_all_oco", "GetPMMarginAccountAllOCO", new([]*OCOOrder)},
		{"derivatives_trading_portfolio_margin/query_margin_accounts_oco", "GetMarginAccountOCO", new(*OCOOrder)},
		{"derivatives_trading_portfolio_margin/query_margin_accounts_open_oco", "GetMarginAccountsOpenOCO", new([]*OCOOrder)},
		{"derivatives_trading_portfolio_margin/query_um_algo_order_history", "GetUMAlgoOrderHistory", new([]*UMAlgoOrder)},
		{"derivatives_trading_portfolio_margin/query_um_modify_order_history", "GetUMOrderModifyHistory", new([]*USDTAmendInfo)},
		{"derivatives_trading_portfolio_margin/query_um_order", "GetUMOrder", new(*UMCMOrder)},
		{"derivatives_trading_portfolio_margin/query_users_cm_force_orders", "GetUsersCMForceOrders", new([]*ForceOrder)},
		{"derivatives_trading_portfolio_margin/query_users_margin_force_orders", "GetUsersMarginForceOrders", new(*MarginForceOrder)},
		{"derivatives_trading_portfolio_margin/query_users_um_force_orders", "GetUsersUMForceOrders", new([]*ForceOrder)},
		{"derivatives_trading_portfolio_margin/um_account_trade_list", "GetUMAccountTradeList", new([]*UMCMAccountTradeItem)},
		{"derivatives_trading_portfolio_margin/um_position_adl_quantile_estimation", "GetUMPositionADLQuantileEstimation", new([]*ADLQuantileEstimation)},
		{"derivatives_trading_portfolio_margin/start_user_data_stream", "CreatePortfolioMarginListenKey", new(*ListenKeyResponse)},
		{"derivatives_trading_portfolio_margin_pro/bnb_transfer", "BNBTransferClassic", new(struct {
			TransactionID int64 `json:"tranId"`
		})},
		{"derivatives_trading_portfolio_margin_pro/change_auto_repay_futures_status", "ChangeAutoRepayFuturesStatusClassic", new(struct {
			Message string `json:"msg"`
		})},
		{"derivatives_trading_portfolio_margin_pro/delete_margin_call_level", "DeletePortfolioMarginCallLevel", new(*DeletePortfolioMarginCallLevelResponse)},
		{"derivatives_trading_portfolio_margin_pro/fund_auto_collection", "ClassicPMFundAutoCollection", new(*FundAutoCollectionResponse)},
		{"derivatives_trading_portfolio_margin_pro/fund_collection_by_asset", "ClassicFundCollectionByAsset", new(*FundAutoCollectionResponse)},
		{"derivatives_trading_portfolio_margin_pro/get_auto_repay_futures_status", "GetAutoRepayFuturesStatusClassic", new(*AutoRepayStatus)},
		{"derivatives_trading_portfolio_margin_pro/get_delta_mode_status", "GetPortfolioDeltaMode", new(*GetPortfolioDeltaModeResponse)},
		{"derivatives_trading_portfolio_margin_pro/get_margin_call_level", "GetPortfolioMarginCallLevel", new(*GetPortfolioMarginCallLevelResponse)},
		{"derivatives_trading_portfolio_margin_pro/get_portfolio_margin_pro_account_balance", "GetPortfolioMarginProBalances", new([]*GetPortfolioMarginProBalancesResponse)},
		{"derivatives_trading_portfolio_margin_pro/get_portfolio_margin_pro_account_info", "GetClassicPortfolioMarginAccountInfo", new(*ClassicPMAccountInfo)},
		{"derivatives_trading_portfolio_margin_pro/get_portfolio_margin_pro_span_account_info", "GetPortfolioMarginProSPANAccount", new(*GetPortfolioMarginProSPANAccountResponse)},
		{"derivatives_trading_portfolio_margin_pro/get_transferable_earn_asset_balance_for_portfolio_margin", "GetPortfolioTransferableEarnBalance", new(*GetPortfolioTransferableEarnBalanceResponse)},
		{"derivatives_trading_portfolio_margin_pro/portfolio_margin_pro_bankruptcy_loan_repay", "RepayClassicPMBankruptacyLoan", new(*FundTransferResponse)},
		{"derivatives_trading_portfolio_margin_pro/query_portfolio_margin_pro_bankruptcy_loan_amount", "GetClassicPortfolioMarginBankruptacyLoanAmount", new(*PMBankruptacyLoanAmount)},
		{"derivatives_trading_portfolio_margin_pro/query_portfolio_margin_pro_bankruptcy_loan_repay_history", "GetPortfolioMarginProLoanRepayments", new(*GetPortfolioMarginProLoanRepaymentsResponse)},
		{"derivatives_trading_portfolio_margin_pro/query_portfolio_margin_pro_negative_balance_interest_history", "GetClassicPMNegativeBalanceInterestHistory", new([]*PMNegativeBalaceInterestHistory)},
		{"derivatives_trading_portfolio_margin_pro/repay_futures_negative_balance", "RepayFuturesNegativeBalanceClassic", new(struct {
			Message string `json:"msg"`
		})},
		{"derivatives_trading_portfolio_margin_pro/set_margin_call_level", "SetPortfolioMarginCallLevel", new(*SetPortfolioMarginCallLevelResponse)},
		{"derivatives_trading_portfolio_margin_pro/switch_delta_mode", "SetPortfolioDeltaMode", new(*SetPortfolioDeltaModeResponse)},
		{"derivatives_trading_portfolio_margin_pro/transfer_ldusdt_rwusd_for_portfolio_margin", "TransferPortfolioEarnAssets", new(*TransferPortfolioEarnAssetsResponse)},
		{"derivatives_trading_portfolio_margin_pro/get_portfolio_margin_asset_leverage", "GetPortfolioMarginAssetLeverage", new([]*PMAssetLeverage)},
		{"derivatives_trading_portfolio_margin_pro/portfolio_margin_collateral_rate", "GetClassicPortfolioMarginCollateralRate", new([]*PMCollateralRate)},
		{"derivatives_trading_portfolio_margin_pro/portfolio_margin_pro_tiered_collateral_rate", "GetPortfolioTieredCollateralRates", new([]*GetPortfolioTieredCollateralRatesResponse)},
		{"derivatives_trading_portfolio_margin_pro/query_portfolio_margin_asset_index_price", "GetPMAssetIndexPrice", new([]*PMIndexPrice)},
		{"derivatives_trading_usds_futures/account_information_v3", "UAccountInformation", new(*UFuturesAccountV3)},
		{"derivatives_trading_usds_futures/futures_account_balance_v3", "UAccountBalance", new([]*UFuturesAccountBalance)},
		{"derivatives_trading_usds_futures/futures_account_configuration", "GetUFuturesAccountConfig", new(*UFuturesAccountConfig)},
		{"derivatives_trading_usds_futures/futures_trading_quantitative_rules_indicators", "UFuturesTradingWuantitativeRulesIndicators", new(*TradingQuantitativeRulesIndicators)},
		{"derivatives_trading_usds_futures/get_bnb_burn_status", "GetUFuturesFeeBurnStatus", new(*UFuturesFeeBurnStatus)},
		{"derivatives_trading_usds_futures/get_current_multi_assets_mode", "GetAssetsMode", new(struct {
			MultiAssetsMargin bool `json:"multiAssetsMargin"`
		})},
		{"derivatives_trading_usds_futures/get_current_position_mode", "GetCurrentPositionMode", new(*PositionMode)},
		{"derivatives_trading_usds_futures/get_download_id_for_futures_order_history", "UFuturesOrderHistoryDownloadID", new(*UTransactionDownloadID)},
		{"derivatives_trading_usds_futures/get_download_id_for_futures_trade_history", "FuturesTradeHistoryDownloadID", new(*UTransactionDownloadID)},
		{"derivatives_trading_usds_futures/get_download_id_for_futures_transaction_history", "GetDownloadIDForFuturesTransactionHistory", new(*UTransactionDownloadID)},
		{"derivatives_trading_usds_futures/get_futures_order_history_download_link_by_id", "GetFuturesOrderHistoryDownloadLinkByID", new(*UTransactionHistoryDownloadLink)},
		{"derivatives_trading_usds_futures/get_futures_trade_download_link_by_id", "FuturesTradeDownloadLinkByID", new(*UTransactionHistoryDownloadLink)},
		{"derivatives_trading_usds_futures/get_futures_transaction_history_download_link_by_id", "GetFuturesTransactionHistoryDownloadLinkByID", new(*UTransactionHistoryDownloadLink)},
		{"derivatives_trading_usds_futures/get_income_history", "GetFuturesUserIncomeHistory", new([]*FuturesUserIncomeDetail)},
		{"derivatives_trading_usds_futures/get_income_history", "UAccountIncomeHistory", new([]*UAccountIncomeHistory)},
		{"derivatives_trading_usds_futures/notional_and_leverage_brackets", "UGetNotionalAndLeverageBrackets", new([]*UNotionalLeverageAndBrakcetsData)},
		{"derivatives_trading_usds_futures/query_user_rate_limit", "GetUSDTUserRateLimits", new([]*RateLimitInfo)},
		{"derivatives_trading_usds_futures/symbol_configuration", "GetUFuturesSymbolConfig", new([]*UFuturesSymbolConfig)},
		{"derivatives_trading_usds_futures/user_commission_rate", "UGetCommissionRates", new(*CommissionRate)},
		{"derivatives_trading_usds_futures/accept_the_offered_quote", "AcceptUFuturesConvertQuote", new(*UFuturesConvertAcceptance)},
		{"derivatives_trading_usds_futures/list_all_convert_pairs", "GetUFuturesConvertPairs", new([]*UFuturesConvertPair)},
		{"derivatives_trading_usds_futures/order_status", "GetUFuturesConvertOrderStatus", new(*UFuturesConvertOrderStatus)},
		{"derivatives_trading_usds_futures/send_quote_request", "SendUFuturesConvertQuoteRequest", new(*UFuturesConvertQuote)},
		{"derivatives_trading_usds_futures/adl_risk", "GetUFuturesSymbolADLRisk", new(UFuturesSymbolADLRisks)},
		{"derivatives_trading_usds_futures/asset_index", "GetMultiAssetModeAssetIndex", new(AssetIndexResponse)},
		{"derivatives_trading_usds_futures/basis", "GetBasis", new([]*BasisInfo)},
		{"derivatives_trading_usds_futures/check_server_time", "UServerTime", new(struct {
			ServerTime types.Time `json:"serverTime"`
		})},
		{"derivatives_trading_usds_futures/composite_index_symbol_information", "UCompositeIndexesInfo", new([]*UCompositeIndexInfoData)},
		{"derivatives_trading_usds_futures/compressed_aggregate_trades_list", "UCompressedTrades", new([]*UCompressedTradeData)},
		{"derivatives_trading_usds_futures/continuous_contract_kline_candlestick_data", "GetUFuturesContinuousKlineData", new([]*UFuturesCandleStick)},
		{"derivatives_trading_usds_futures/get_funding_rate_history", "UGetFundingHistory", new([]*FundingRateHistory)},
		{"derivatives_trading_usds_futures/get_funding_rate_info", "UGetFundingRateInfo", new([]*FundingRateInfoResponse)},
		{"derivatives_trading_usds_futures/index_price_kline_candlestick_data", "GetIndexPriceKlineData", new([]*UFuturesCandleStick)},
		{"derivatives_trading_usds_futures/kline_candlestick_data", "UKlineData", new([]*UFuturesCandleStick)},
		{"derivatives_trading_usds_futures/long_short_ratio", "UGlobalLongShortRatio", new([]*ULongShortRatio)},
		{"derivatives_trading_usds_futures/mark_price", "UGetMarkPrice", new(UMarkPrice)},
		{"derivatives_trading_usds_futures/mark_price_kline_candlestick_data", "GetMarkPriceKlineCandlesticks", new([]*UFuturesCandleStick)},
		{"derivatives_trading_usds_futures/old_trades_lookup", "UFuturesHistoricalTrades", new([]*UPublicTradesData)},
		{"derivatives_trading_usds_futures/open_interest", "UOpenInterest", new(*UOpenInterestData)},
		{"derivatives_trading_usds_futures/open_interest_statistics", "UOpenInterestStats", new([]*UOpenInterestStats)},
		{"derivatives_trading_usds_futures/order_book", "UFuturesOrderbook", new(*OrderBook)},
		{"derivatives_trading_usds_futures/premium_index_kline_data", "GetPremiumIndexKlineCandlesticks", new([]*UFuturesCandleStick)},
		{"derivatives_trading_usds_futures/quarterly_contract_settlement_price", "GetQuarterlyContractSettlementPrice", new([]*SettlementPrice)},
		{"derivatives_trading_usds_futures/query_index_price_constituents", "GetIndexPriceConstituents", new(*IndexPriceConstituent)},
		{"derivatives_trading_usds_futures/query_index_price_constituents", "GetUFuturesIndexConstituents", new(*UFuturesIndexConstituents)},
		{"derivatives_trading_usds_futures/query_insurance_fund_balance_snapshot", "GetUFuturesInsuranceBalance", new(UFuturesInsuranceBalances)},
		{"derivatives_trading_usds_futures/recent_trades_list", "URecentTrades", new([]*UPublicTradesData)},
		{"derivatives_trading_usds_futures/rpi_order_book", "GetURPIOrderbook", new(*RPIResponse)},
		{"derivatives_trading_usds_futures/symbol_order_book_ticker", "USymbolOrderbookTicker", new(USymbolOrderbookTicker)},
		{"derivatives_trading_usds_futures/symbol_price_ticker_v2", "USymbolPriceTicker", new(USymbolPriceTicker)},
		{"derivatives_trading_usds_futures/taker_buy_sell_volume", "UTakerBuySellVol", new([]*UTakerVolumeData)},
		{"derivatives_trading_usds_futures/ticker24hr_price_change_statistics", "U24HTickerPriceChangeStats", new(U24HrPriceChangeStats)},
		{"derivatives_trading_usds_futures/top_trader_long_short_ratio_accounts", "UTopAccountsLongShortRatio", new([]*ULongShortRatio)},
		{"derivatives_trading_usds_futures/top_trader_long_short_ratio_positions", "UTopPositionsLongShortRatio", new([]*ULongShortRatio)},
		{"derivatives_trading_usds_futures/trading_schedule", "GetUFuturesTradingSchedule", new(*UFuturesTradingSchedule)},
		{"derivatives_trading_usds_futures/classic_portfolio_margin_account_information", "GetUFuturesPortfolioMarginAccountInfo", new(*ClassicPortfolioMarginAccountInfo)},
		{"derivatives_trading_usds_futures/account_trade_list", "UAccountTradesHistory", new([]*UAccountTradeHistory)},
		{"derivatives_trading_usds_futures/all_orders", "UAllAccountOrders", new([]*UFuturesOrderData)},
		{"derivatives_trading_usds_futures/auto_cancel_all_open_orders", "UAutoCancelAllOpenOrders", new(*AutoCancelAllOrdersData)},
		{"derivatives_trading_usds_futures/cancel_algo_order", "UFuturesCancelAlgoOrder", new(*UFuturesAlgoOrderCancelResponse)},
		{"derivatives_trading_usds_futures/cancel_all_algo_open_orders", "UFuturesCancelAllAlgoOrders", new(*UFuturesAlgoOrderCancelResponse)},
		{"derivatives_trading_usds_futures/cancel_all_open_orders", "UCancelAllOpenOrders", new(*GenericAuthResponse)},
		{"derivatives_trading_usds_futures/cancel_multiple_orders", "UCancelBatchOrders", new([]*UOrderData)},
		{"derivatives_trading_usds_futures/cancel_order", "UCancelOrder", new(*UOrderData)},
		{"derivatives_trading_usds_futures/change_initial_leverage", "UChangeInitialLeverageRequest", new(*UChangeInitialLeverage)},
		{"derivatives_trading_usds_futures/current_all_algo_open_orders", "UFuturesOpenAlgoOrders", new([]*UFuturesAlgoOrder)},
		{"derivatives_trading_usds_futures/current_all_open_orders", "UAllAccountOpenOrders", new([]*UOrderData)},
		{"derivatives_trading_usds_futures/get_order_modify_history", "GetUSDTOrderModifyHistory", new([]*USDTAmendInfo)},
		{"derivatives_trading_usds_futures/get_position_margin_change_history", "UPositionMarginChangeHistory", new([]*UPositionMarginChangeHistoryData)},
		{"derivatives_trading_usds_futures/modify_isolated_position_margin", "UModifyIsolatedPositionMarginReq", new(*UModifyIsolatedPosMargin)},
		{"derivatives_trading_usds_futures/modify_multiple_orders", "UModifyMultipleOrders", new([]*UOrderData)},
		{"derivatives_trading_usds_futures/modify_order", "UModifyOrder", new(*UOrderData)},
		{"derivatives_trading_usds_futures/new_algo_order", "UFuturesNewAlgoOrder", new(*UFuturesAlgoOrder)},
		{"derivatives_trading_usds_futures/new_order", "UFuturesNewOrder", new(*UOrderData)},
		{"derivatives_trading_usds_futures/place_multiple_orders", "UPlaceBatchOrders", new([]*UOrderData)},
		{"derivatives_trading_usds_futures/position_adl_quantile_estimation", "UPositionsADLEstimate", new([]*UPositionADLEstimationData)},
		{"derivatives_trading_usds_futures/position_information_v3", "UPositionsInfo", new([]*UFuturesPositionV3)},
		{"derivatives_trading_usds_futures/query_algo_order", "UFuturesGetAlgoOrder", new(*UFuturesAlgoOrder)},
		{"derivatives_trading_usds_futures/query_all_algo_orders", "UFuturesAllAlgoOrders", new([]*UFuturesAlgoOrder)},
		{"derivatives_trading_usds_futures/query_current_open_order", "UFetchOpenOrder", new(*UOrderData)},
		{"derivatives_trading_usds_futures/query_order", "UGetOrderData", new(*UOrderData)},
		{"derivatives_trading_usds_futures/test_order", "UFuturesTestNewOrder", new(*UOrderData)},
		{"derivatives_trading_usds_futures/users_force_orders", "UAccountForcedOrders", new([]*UForceOrdersData)},
		{"derivatives_trading_usds_futures/keepalive_user_data_stream", "KeepUFuturesListenKeyAlive", new(*ListenKeyResponse)},
		{"derivatives_trading_usds_futures/start_user_data_stream", "CreateUFuturesListenKey", new(*ListenKeyResponse)},
		{"dual_investment/get_dual_investment_product_list", "GetDualInvestmentProductList", new(*DualInvestmentProduct)},
		{"dual_investment/change_auto_compound_status", "ChangeAutoCompoundStatus", new(*AutoCompoundStatus)},
		{"dual_investment/check_dual_investment_accounts", "CheckDualInvestmentAccounts", new(*DualInvestmentAccount)},
		{"dual_investment/get_dual_investment_positions", "GetDualInvestmentPositions", new(*DualInvestmentPositions)},
		{"dual_investment/subscribe_dual_investment_products", "SubscribeDualInvestmentProducts", new(*DualInvestmentProductSubscription)},
		{"fiat/deposit", "DepositFiat", new(*FiatOrderResponse)},
		{"fiat/fiat_withdraw", "WithdrawFiat", new(*FiatOrderResponse)},
		{"fiat/get_fiat_deposit_withdraw_history", "GetFiatDepositAndWithdrawalHistory", new(*FiatTransactionHistory)},
		{"fiat/get_fiat_payments_history", "GetFiatPaymentHistory", new(*FiatPaymentHistory)},
		{"fiat/get_order_detail", "GetFiatOrderDetail", new(*FiatOrderDetail)},
		{"gift_card/create_a_dual_token_gift_card", "CreateDualTokenGiftCard", new(*DualTokenGiftCard)},
		{"gift_card/create_a_single_token_gift_card", "CreateSingleTokenGiftCard", new(*GiftCard)},
		{"gift_card/fetch_rsa_public_key", "FetchRSAPublicKey", new(*RSAPublicKeyResponse)},
		{"gift_card/fetch_token_limit", "FetchTokenLimit", new(*TokenLimitInfo)},
		{"gift_card/redeem_a_binance_gift_card", "RedeemBinanaceGiftCard", new(*RedeemBinanceGiftCard)},
		{"gift_card/verify_binance_gift_card_by_gift_card_number", "VerifyBinanceGiftCardNumber", new(*GiftCardVerificationResponse)},
		{"margin_trading/adjust_cross_margin_max_leverage", "AdjustCrossMarginMaxLeverage", new(struct {
			Success bool `json:"success"`
		})},
		{"margin_trading/disable_isolated_margin_account", "DisableIsolatedMarginAccount", new(*IsolatedMarginResponse)},
		{"margin_trading/enable_isolated_margin_account", "EnableIsolatedMarginAccount", new(*IsolatedMarginResponse)},
		{"margin_trading/get_bnb_burn_status", "GetBNBBurnStatus", new(*BNBBurnOnSpotAndMarginInterest)},
		{"margin_trading/get_summary_of_margin_account", "GetSummaryOfMarginAccount", new(*MarginAccountSummary)},
		{"margin_trading/query_cross_isolated_margin_capital_flow", "GetCrossOrIsolatedMarginCapitalFlow", new([]*MarginCapitalFlow)},
		{"margin_trading/query_cross_margin_account_details", "GetCrossMarginAccountDetail", new(*CrossMarginAccount)},
		{"margin_trading/query_cross_margin_account_details", "GetMarginAccount", new(*MarginAccount)},
		{"margin_trading/query_cross_margin_fee_data", "GetCrossMarginFeeData", new([]*CrossMarginFeeData)},
		{"margin_trading/query_enabled_isolated_margin_account_limit", "GetEnabledIsolatedMarginAccountLimit", new(*IsolatedMarginAccountLimit)},
		{"margin_trading/query_isolated_margin_account_info", "GetIsolatedMarginAccountInfo", new(*IsolatedMarginAccountInfo)},
		{"margin_trading/query_isolated_margin_fee_data", "GetIsolatedMaringFeeData", new([]*IsolatedMarginFeeData)},
		{"margin_trading/get_future_hourly_interest_rate", "GetFutureHourlyInterestRate", new([]*HourlyInterestrate)},
		{"margin_trading/get_interest_history", "GetUserMarginInterestHistory", new(*UserMarginInterestHistoryResponse)},
		{"margin_trading/margin_account_borrow_repay", "MarginAccountBorrowRepay", new(struct {
			TransactionID types.PreciseNumber `json:"tranId"`
		})},
		{"margin_trading/query_borrow_repay_records_in_margin_account", "GetBorrowOrRepayRecordsInMarginAccount", new(*MarginAccountBorrowRepayRecords)},
		{"margin_trading/query_margin_interest_rate_history", "GetMarginInterestRateHistory", new([]*MarginInterestRate)},
		{"margin_trading/query_max_borrow", "GetMaxBorrow", new(*MaxBorrow)},
		{"margin_trading/cross_margin_collateral_ratio", "GetCrossMarginCollateralRatio", new([]*CrossMarginCollateralRatio)},
		{"margin_trading/get_all_cross_margin_pairs", "GetAllCrossMarginPairs", new([]*CrossMarginPairInfo)},
		{"margin_trading/get_all_isolated_margin_symbol", "GetAllIsolatedMarginSymbols", new([]*IsolatedMarginAccount)},
		{"margin_trading/get_all_margin_assets", "GetAllMarginAssets", new([]*MarginAsset)},
		{"margin_trading/get_delist_schedule", "GetTokensOrSymbolsDelistSchedule", new([]*MarginDelistSchedule)},
		{"margin_trading/get_limit_price_pairs", "GetMarginLimitPricePairs", new(*MarginLimitPricePairs)},
		{"margin_trading/get_list_schedule", "GetMarginListSchedule", new([]*MarginListSchedule)},
		{"margin_trading/get_margin_asset_risk_based_liquidation_ratio", "GetMarginAssetLiquidationRatios", new([]*MarginAssetLiquidationRatio)},
		{"margin_trading/get_margin_restricted_assets", "GetMarginRestrictedAssets", new(*MarginRestrictedAssetsResponse)},
		{"margin_trading/query_isolated_margin_tier_data", "GetIsolatedMarginTierData", new([]*IsolatedMarginTierInfo)},
		{"margin_trading/query_liability_coin_leverage_bracket_in_cross_margin_pro_mode", "GetLiabilityCoinLeverageBracketInCrossMarginProMode", new([]*LiabilityCoinLeverageBracket)},
		{"margin_trading/query_margin_available_inventory", "GetMarginAvailableInventory", new(*MarginInventory)},
		{"margin_trading/query_margin_priceindex", "GetMarginPriceIndex", new(*MarginPriceIndex)},
		{"margin_trading/create_special_key", "CreateMarginSpecialKey", new(*MarginSpecialKey)},
		{"margin_trading/get_force_liquidation_record", "GetForceLiquidiationRecord", new(*LiquidiationRecord)},
		{"margin_trading/get_small_liability_exchange_coin_list", "GetSmallLiabilityExchangeCoinList", new([]*SmallLiabilityCoin)},
		{"margin_trading/get_small_liability_exchange_history", "GetSmallLiabilityExchangeHistory", new(*SmallLiabilityExchange)},
		{"margin_trading/liquidation_loan_repay", "RepayMarginLiquidationLoan", new(*MarginLiquidationLoanRepayment)},
		{"margin_trading/margin_account_cancel_all_open_orders_on_a_symbol", "CancelAllOpenMarginAccountOrdersOnSymbol", new([]*MarginAccountOrderDetail)},
		{"margin_trading/margin_account_cancel_oco", "CancelMarginAccountOCOOrder", new(*OCOOrder)},
		{"margin_trading/margin_account_cancel_order", "CancelMarginAccountOrder", new(*MarginAccountOrder)},
		{"margin_trading/margin_account_new_oco", "NewMarginAccountOCOOrder", new(*OCOOrder)},
		{"margin_trading/margin_account_new_order", "PostMarginAccountOrder", new(*MarginAccountOrder)},
		{"margin_trading/margin_account_new_oto", "NewMarginOTOOrderList", new(*MarginOrderList)},
		{"margin_trading/margin_account_new_otoco", "NewMarginOTOCOOrderList", new(*MarginOrderList)},
		{"margin_trading/margin_manual_liquidation", "MarginManualLiquidiation", new(*SmallLiabilityCoin)},
		{"margin_trading/query_current_margin_order_count_usage", "GetCurrencyMarginOrderCountUsage", new([]*MarginOrderCount)},
		{"margin_trading/query_liquidation_loan", "GetMarginLiquidationLoan", new(*GetMarginLiquidationLoanResponse)},
		{"margin_trading/query_liquidation_loan_repay_history", "GetMarginLiquidationLoanRepayHistory", new(*MarginLiquidationLoanRepayHistory)},
		{"margin_trading/query_margin_accounts_all_oco", "GetMarginAccountAllOCO", new([]*OCOOrder)},
		{"margin_trading/query_margin_accounts_all_orders", "GetMarginAccountAllOrders", new([]*TradeOrder)},
		{"margin_trading/query_margin_accounts_oco", "GetMarginAccountOCOOrder", new(*OCOOrder)},
		{"margin_trading/query_margin_accounts_open_oco", "GetMarginAccountsOpenOCOOrder", new([]*OCOOrder)},
		{"margin_trading/query_margin_accounts_open_orders", "GetMarginAccountsOpenOrders", new([]*TradeOrder)},
		{"margin_trading/query_margin_accounts_order", "GetMarginAccountsOrder", new(*TradeOrder)},
		{"margin_trading/query_margin_accounts_trade_list", "GetMarginAccountTradeList", new([]*TradeHistory)},
		{"margin_trading/query_prevented_matches", "GetMarginPreventedMatches", new([]*MarginPreventedMatch)},
		{"margin_trading/query_special_key", "GetMarginSpecialKey", new(*MarginSpecialKey)},
		{"margin_trading/query_special_key_list", "GetMarginSpecialKeyList", new([]*MarginSpecialKey)},
		{"margin_trading/get_cross_margin_transfer_history", "GetCrossMarginTransferHistory", new(*CrossMarginTransferHistory)},
		{"margin_trading/query_max_transfer_out_amount", "GetMaxTransferOutAmount", new(struct {
			Amount types.Number `json:"amount"`
		})},
		{"margin_trading/start_user_data_stream", "CreateMarginListenKey", new(*ListenKeyResponse)},
		{"mining/account_list", "GetAccountList", new(*MiningAccounts)},
		{"mining/acquiring_algorithm", "AcquiringAlgorithm", new(*AlgorithmsList)},
		{"mining/acquiring_coinname", "GetCoinNames", new(*CoinNames)},
		{"mining/cancel_hashrate_resale_configuration", "CancelHashrateRescaleConfiguration", new(*HashrateRescaleCancelResponse)},
		{"mining/earnings_list", "GetEarningList", new(*EarningList)},
		{"mining/extra_bonus_list", "ExtraBonousList", new(*ExtraBonus)},
		{"mining/hashrate_resale_detail", "GetHashRateRescaleDetail", new(*HashrateRescaleDetail)},
		{"mining/hashrate_resale_list", "GetHashrateRescaleList", new(*HashrateHashTransfers)},
		{"mining/hashrate_resale_request", "HashRateRescaleRequest", new(*HashrateRescalResponse)},
		{"mining/mining_account_earning", "GetMiningAccountEarningRate", new(*MiningAccountEarnings)},
		{"mining/request_for_detail_miner_list", "GetDetailMinerList", new(*MinersDetailList)},
		{"mining/request_for_miner_list", "GetMinersList", new(*MinerLists)},
		{"mining/statistic_list", "StatisticsList", new(*UserStatistics)},
		{"pay/get_pay_trade_history", "GetPayTradeHistory", new(*PayTradeHistory)},
		{"rebate/get_spot_rebate_history_records", "GetSpotRebateHistoryRecords", new(*RebateHistory)},
		{"simple_earn/get_bfusd_account", "GetBFUSDAccount", new(*BFUSDAccount)},
		{"simple_earn/get_bfusd_quota_details", "GetBFUSDQuota", new(*StablecoinYieldQuota)},
		{"simple_earn/get_bfusd_rate_history", "GetBFUSDRateHistory", new(*StablecoinYieldRateHistory)},
		{"simple_earn/get_bfusd_redemption_history", "GetBFUSDRedemptionHistory", new(*StablecoinYieldRedemptionHistory)},
		{"simple_earn/get_bfusd_rewards_history", "GetBFUSDRewardsHistory", new(*StablecoinYieldRewardsHistory)},
		{"simple_earn/get_bfusd_subscription_history", "GetBFUSDSubscriptionHistory", new(*StablecoinYieldSubscriptionHistory)},
		{"simple_earn/redeem_bfusd", "RedeemBFUSD", new(*StablecoinYieldRedemption)},
		{"simple_earn/subscribe_bfusd", "SubscribeBFUSD", new(*StablecoinYieldSubscription)},
		{"simple_earn/get_collateral_record", "GetSimpleEarnCollateralRecord", new(*SimpleEarnCollateralRecords)},
		{"simple_earn/get_flexible_personal_left_quota", "GetFlexiblePersonalLeftQuota", new(*PersonalLeftQuota)},
		{"simple_earn/get_flexible_product_position", "GetFlexibleProductPosition", new(*FlexibleProductPosition)},
		{"simple_earn/get_flexible_redemption_record", "GetFlexibleRedemptionRecord", new(*RedemptionRecord)},
		{"simple_earn/get_flexible_rewards_history", "GetFlexibleRewardHistory", new(*FlexibleReward)},
		{"simple_earn/get_flexible_subscription_preview", "GetFlexibleSubscriptionPreview", new(*FlexibleSubscriptionPreview)},
		{"simple_earn/get_flexible_subscription_record", "GetFlexibleSubscriptionRecord", new(*FlexibleSubscriptionRecord)},
		{"simple_earn/get_locked_personal_left_quota", "GetLockedPersonalLeftQuota", new(*PersonalLeftQuota)},
		{"simple_earn/get_locked_product_position", "GetLockedProductPosition", new(*LockedProductPosition)},
		{"simple_earn/get_locked_redemption_record", "GetLockedRedemptionRecord", new(*LockedRedemptionRecord)},
		{"simple_earn/get_locked_rewards_history", "GetLockedRewardHistory", new(*LockedRewards)},
		{"simple_earn/get_locked_subscription_preview", "GetLockedSubscriptionPreview", new([]*LockedSubscriptionPreview)},
		{"simple_earn/get_locked_subscription_record", "GetLockedSubscriptionsRecords", new(*LockedSubscriptions)},
		{"simple_earn/get_rate_history", "GetSimpleEarnRatehistory", new(*SimpleEarnRateHistory)},
		{"simple_earn/get_simple_earn_flexible_product_list", "GetSimpleEarnFlexibleProductList", new(*SimpleEarnProducts)},
		{"simple_earn/get_simple_earn_locked_product_list", "GetSimpleEarnLockedProducts", new(*LockedSimpleEarnProducts)},
		{"simple_earn/redeem_flexible_product", "RedeemFlexibleProduct", new(*RedeemResponse)},
		{"simple_earn/redeem_locked_product", "RedeemLockedProduct", new(*RedeemResponse)},
		{"simple_earn/set_flexible_auto_subscribe", "SetFlexibleAutoSusbcribe", new(struct {
			Success bool `json:"success"`
		})},
		{"simple_earn/set_locked_auto_subscribe", "SetLockedAutoSubscribe", new(struct {
			Success bool `json:"success"`
		})},
		{"simple_earn/set_locked_product_redeem_option", "SetLockedProductRedeemOption", new(struct {
			Success bool `json:"success"`
		})},
		{"simple_earn/simple_account", "SimpleAccount", new(*SimpleAccount)},
		{"simple_earn/subscribe_flexible_product", "SubscribeToFlexibleProducts", new(*SimpleEarnSubscriptionResponse)},
		{"simple_earn/subscribe_locked_product", "SubscribeToLockedProducts", new(*SimpleEarnSubscriptionResponse)},
		{"simple_earn/get_rwusd_account", "GetRWUSDAccount", new(*RWUSDAccount)},
		{"simple_earn/get_rwusd_quota_details", "GetRWUSDQuota", new(*StablecoinYieldQuota)},
		{"simple_earn/get_rwusd_rate_history", "GetRWUSDRateHistory", new(*StablecoinYieldRateHistory)},
		{"simple_earn/get_rwusd_redemption_history", "GetRWUSDRedemptionHistory", new(*StablecoinYieldRedemptionHistory)},
		{"simple_earn/get_rwusd_rewards_history", "GetRWUSDRewardsHistory", new(*StablecoinYieldRewardsHistory)},
		{"simple_earn/get_rwusd_subscription_history", "GetRWUSDSubscriptionHistory", new(*StablecoinYieldSubscriptionHistory)},
		{"simple_earn/redeem_rwusd", "RedeemRWUSD", new(*StablecoinYieldRedemption)},
		{"simple_earn/subscribe_rwusd", "SubscribeRWUSD", new(*StablecoinYieldSubscription)},
		{"simple_earn/get_yield_arena_activities", "GetYieldArenaActivities", new(*YieldArenaActivities)},
		{"spot/account_commission", "GetCommissionRates", new(*AccountCommissionRate)},
		{"spot/all_order_list", "GetAllOCOOrders", new([]*OCOOrder)},
		{"spot/all_orders", "AllOrders", new([]*TradeOrder)},
		{"spot/get_account", "GetAccount", new(struct {
			Response
			Account
		})},
		{"spot/get_open_orders", "OpenOrders", new([]*TradeOrder)},
		{"spot/get_order", "QueryOrder", new(*TradeOrder)},
		{"spot/get_order_list", "GetOCOOrders", new(*OCOOrder)},
		{"spot/my_allocations", "GetAllocations", new([]*Allocation)},
		{"spot/my_filters", "GetAccountSymbolFilters", new(*AccountFiltersResponse)},
		{"spot/my_prevented_matches", "GetPreventedMatches", new([]*PreventedMatches)},
		{"spot/my_trades", "GetAccountTradeList", new([]*AccountTradeItem)},
		{"spot/open_order_list", "GetOpenOCOList", new([]*OCOOrder)},
		{"spot/order_amendments", "GetOrderAmendments", new([]*OrderAmendment)},
		{"spot/rate_limit_order", "GetCurrentOrderCountUsage", new([]*CurrentOrderCountUsage)},
		{"spot/exchange_info", "GetExchangeInfo", new(*ExchangeInfo)},
		{"spot/execution_rules", "GetExecutionRules", new(*SymbolExecutionRules)},
		{"spot/time", "GetExchangeServerTime", new(struct {
			ServerTime types.Time `json:"serverTime"`
		})},
		{"spot/agg_trades", "GetAggregatedTrades", new([]*AggregatedTrade)},
		{"spot/avg_price", "GetAveragePrice", new(*AveragePrice)},
		{"spot/depth", "GetOrderBook", new(*OrderBook)},
		{"spot/get_trades", "GetMostRecentTrades", new([]*RecentTrade)},
		{"spot/historical_block_trades", "GetHistoricalBlockTrades", new([]*HistoricalBlockTrade)},
		{"spot/historical_trades", "GetHistoricalTrades", new([]*HistoricalTrade)},
		{"spot/klines", "GetSpotKline", new([]*CandleStick)},
		{"spot/reference_price", "GetSpotReferencePrice", new(*ReferencePrice)},
		{"spot/reference_price_calculation", "GetSpotReferencePriceCalculation", new(*ReferencePriceCalculation)},
		{"spot/ticker", "GetTickerData", new(PriceChanges)},
		{"spot/ticker24hr", "GetPriceChangeStats", new(PriceChanges)},
		{"spot/ticker_book_ticker", "GetBestPrice", new(BestPrices)},
		{"spot/ticker_price", "GetLatestSpotPrice", new(SymbolPrices)},
		{"spot/ticker_trading_day", "GetTradingDayTicker", new(PriceChanges)},
		{"spot/ui_klines", "GetUIKline", new([]*CandleStick)},
		{"spot/delete_open_orders", "CancelAllOpenOrderOnSymbol", new([]*SymbolOrders)},
		{"spot/delete_order", "CancelExistingOrder", new(*CancelOrderResponse)},
		{"spot/delete_order_list", "CancelOCOOrder", new(*OCOOrder)},
		{"spot/new_order", "NewOrder", new(NewOrderResponse)},
		{"spot/order_amend_keep_priority", "AmendOrderKeepPriority", new(*AmendKeepPriorityResponse)},
		{"spot/order_cancel_replace", "CancelExistingOrderAndSendNewOrder", new(*CancelAndReplaceResponse)},
		{"spot/order_list_oco", "NewOCOOrderList", new(*OCOListOrderResponse)},
		{"spot/order_list_opo", "NewOPOOrderList", new(*OCOOrder)},
		{"spot/order_list_opoco", "NewOPOCOOrderList", new(*OCOOrder)},
		{"spot/order_list_oto", "NewOTOOrderList", new(*OCOOrder)},
		{"spot/order_list_otoco", "NewOTOCOOrderList", new(*OCOOrder)},
		{"spot/order_oco", "NewOCOOrder", new(*OCOOrder)},
		{"spot/order_test", "NewOrderTest", new(*TestOrderResponse)},
		{"spot/sor_order", "NewOrderUsingSOR", new(*SOROrderResponse)},
		{"spot/sor_order_test", "NewOrderUsingSORTest", new(*TestOrderResponse)},
		{"staking/eth_staking_account", "GetETHStakingAccount", new(*StakingAccountV2Response)},
		{"staking/get_current_eth_staking_quota", "GetCurrentETHStakingQuota", new(*ETHStakingQuota)},
		{"staking/get_eth_redemption_history", "GetETHRedemptionHistory", new(*ETHRedemptionHistory)},
		{"staking/get_eth_staking_history", "GetETHStakingHistory", new(*ETHStakingHistory)},
		{"staking/get_wbeth_rate_history", "GetWBETHRateHistory", new(*WBETHRateHistory)},
		{"staking/get_wbeth_rewards_history", "GetWBETHRewardHistory", new(*WBETHRewardHistory)},
		{"staking/get_wbeth_unwrap_history", "GetWBETHUnwrapHistory", new(*WBETHWrapHistory)},
		{"staking/get_wbeth_wrap_history", "GetWBETHWrapHistory", new(*WBETHWrapHistory)},
		{"staking/redeem_eth", "RedeemETH", new(*StakingRedemptionResponse)},
		{"staking/subscribe_eth_staking", "SubscribeETHStaking", new(*StakingSubscriptionResponse)},
		{"staking/wrap_beth", "WrapBETH", new(*WrapBETHResponse)},
		{"staking/get_on_chain_yields_locked_personal_left_quota", "GetOnChainYieldsLeftQuota", new(*OnChainYieldsLeftQuota)},
		{"staking/get_on_chain_yields_locked_product_list", "GetOnChainYieldsLockedProducts", new(*OnChainYieldsLockedProducts)},
		{"staking/get_on_chain_yields_locked_product_position", "GetOnChainYieldsPositions", new(*OnChainYieldsPositions)},
		{"staking/get_on_chain_yields_locked_redemption_record", "GetOnChainYieldsRedemptionRecords", new(*OnChainYieldsRedemptionRecords)},
		{"staking/get_on_chain_yields_locked_rewards_history", "GetOnChainYieldsRewardsRecords", new(*OnChainYieldsRewardsRecords)},
		{"staking/get_on_chain_yields_locked_subscription_preview", "GetOnChainYieldsSubscriptionPreview", new(*OnChainYieldsSubscriptionPreview)},
		{"staking/get_on_chain_yields_locked_subscription_record", "GetOnChainYieldsSubscriptionRecords", new(*OnChainYieldsSubscriptionRecords)},
		{"staking/on_chain_yields_account", "GetOnChainYieldsAccount", new(*OnChainYieldsAccount)},
		{"staking/redeem_on_chain_yields_locked_product", "RedeemOnChainYieldsLockedProduct", new(*SuccessResponse)},
		{"staking/set_on_chain_yields_locked_auto_subscribe", "SetOnChainYieldsAutoSubscribe", new(*SuccessResponse)},
		{"staking/set_on_chain_yields_locked_product_redeem_option", "SetOnChainYieldsRedeemOption", new(*SuccessResponse)},
		{"staking/subscribe_on_chain_yields_locked_product", "SubscribeOnChainYieldsLockedProduct", new(*OnChainYieldsSubscription)},
		{"staking/get_soft_staking_product_list", "GetSoftStakingProducts", new(*SoftStakingProducts)},
		{"staking/get_soft_staking_rewards_history", "GetSoftStakingRewardsRecords", new(*SoftStakingRewardsRecords)},
		{"staking/set_soft_staking", "SetSoftStaking", new(*SuccessResponse)},
		{"staking/claim_boost_rewards", "ClaimBoostRewards", new(struct {
			Success bool `json:"success"`
		})},
		{"staking/get_bnsol_rate_history", "GetBNSOLRateHistory", new(*BNSOLRewardHistory)},
		{"staking/get_bnsol_rewards_history", "GetBNSOLRewardsHistory", new(*BNSOLRewardHistory)},
		{"staking/get_boost_rewards_history", "GetBoostRewardsHistory", new(*RewardBoostResponse)},
		{"staking/get_sol_redemption_history", "GetSOLRedemptionHistory", new(*SOLStakingHistory)},
		{"staking/get_sol_staking_history", "GetSOLStakingHistory", new(*SOLStakingHistory)},
		{"staking/get_sol_staking_quota_details", "GetSOLStakingQuotaDetails", new(*SOLStakingQuotaDetail)},
		{"staking/get_unclaimed_rewards", "GetUnclaimedRewards", new([]*Reward)},
		{"staking/redeem_sol", "RedeemSOL", new(*SOLRedemptionResponse)},
		{"staking/sol_staking_account", "GetSOLStakingAccount", new(*SOLStakingAccountDetail)},
		{"staking/subscribe_sol_staking", "SubscribeToSOLStaking", new(*SOLStakingSubscriptionResponse)},
		{"sub_account/create_a_virtual_sub_account", "CreateVirtualSubAccount", new(*VirtualSubAccount)},
		{"sub_account/enable_futures_for_sub_account", "EnableFuturesSubAccount", new(*FuturesEnablingResponse)},
		{"sub_account/enable_options_for_sub_account", "EnableOptionsForSubAccount", new(*OptionsEnablingResponse)},
		{"sub_account/get_futures_position_risk_of_sub_account_v2", "GetV2FuturesPositionRiskSubAccount", new(*SubAccountFuturesPositionRisk)},
		{"sub_account/get_sub_accounts_status_on_margin_or_futures", "GetSubAccountStatusOnMarginFutures", new([]*SubAccountStatus)},
		{"sub_account/query_sub_account_list", "GetSubAccountList", new(*SubAccountList)},
		{"sub_account/query_sub_account_transaction_statistics", "GetSubAccountTransactionStatistics", new(*SubAccountTransactionStatistics)},
		{"sub_account/add_ip_restriction_for_sub_account_api_key", "AddIPRestrictionForSubAccountAPIkey", new(*APIRestrictions)},
		{"sub_account/create_sub_account_api_key", "CreateSubAccountAPIKey", new(*SubAccountAPIKeyDetail)},
		{"sub_account/delete_ip_list_for_a_sub_account_api_key", "DeleteIPListForSubAccountAPIKey", new(*APIRestrictions)},
		{"sub_account/get_ip_restriction_for_a_sub_account_api_key", "GetIPRestrictionForSubAccountAPIKey", new(*APIRestrictions)},
		{"sub_account/modify_sub_account_api_key_permission", "ModifySubAccountAPIKeyPermission", new(*SubAccountAPIKeyDetail)},
		{"sub_account/query_sub_account_api_key", "GetSubAccountAPIKeys", new(*SubAccountAPIKeys)},
		{"sub_account/futures_transfer_for_sub_account", "FuturesTransferSubAccount", new(struct {
			TransactionID string `json:"txnId"`
		})},
		{"sub_account/get_detail_on_sub_accounts_futures_account_v2", "GetDetailOnSubAccountsFuturesAccount", new(*MarginedFuturesAccount)},
		{"sub_account/get_detail_on_sub_accounts_margin_account", "GetDetailOnSubAccountMarginAccount", new(*SubAccountMarginAccountDetail)},
		{"sub_account/get_move_position_history_for_sub_account", "GetSubAccountMovePositionHistory", new(*SubAccountMovePositionHistory)},
		{"sub_account/get_sub_account_deposit_address", "GetSubAccountDepositAddress", new(*SubAccountDepositAddress)},
		{"sub_account/get_sub_account_deposit_history", "GetSubAccountDepositHistory", new([]*SubAccountDepositHistory)},
		{"sub_account/get_summary_of_sub_accounts_futures_account_v2", "GetSummaryOfSubAccountsFuturesAccount", new(*AccountSummary)},
		{"sub_account/get_summary_of_sub_accounts_margin_account", "GetSummaryOfSubAccountMarginAccount", new(*SubAccountMarginAccount)},
		{"sub_account/margin_transfer_for_sub_account", "MarginTransferForSubAccount", new(struct {
			TransactionID string `json:"txnId"`
		})},
		{"sub_account/move_position_for_sub_account", "MoveSubAccountPosition", new(*SubAccountMovePositionResult)},
		{"sub_account/query_sub_account_assets_asset_management", "GetSubAccountAssets", new(*SubAccountAssets)},
		{"sub_account/query_sub_account_futures_asset_transfer_history", "GetSubAccountFuturesAssetTransferHistory", new(*AssetTransferHistory)},
		{"sub_account/query_sub_account_spot_asset_transfer_history", "GetSubAccountSpotAssetTransferHistory", new([]*SubAccountSpotAsset)},
		{"sub_account/query_sub_account_spot_assets_summary", "GetSubAccountSpotAssetsSummary", new(*SubAccountSpotSummary)},
		{"sub_account/query_universal_transfer_history", "GetUniversalTransferHistoryForMasterAccount", new(*UniversalTransfersDetail)},
		{"sub_account/sub_account_futures_asset_transfer", "SubAccountFuturesAssetTransfer", new(*FuturesAssetTransfer)},
		{"sub_account/sub_account_transfer_history", "SubAccountTransferHistory", new([]*SubAccountTransferHistory)},
		{"sub_account/sub_account_transfer_history", "SubAccountTransferHistoryForSubAccount", new([]*SubAccountTransferHistoryItem)},
		{"sub_account/transfer_to_master", "FromSubAccountTransferToMaster", new(struct {
			TransactionID string `json:"txnId"`
		})},
		{"sub_account/transfer_to_sub_account_of_same_master", "TransferToSubAccountOfSameMaster", new(struct {
			TransactionID string `json:"txnId"`
		})},
		{"sub_account/universal_transfer", "UniversalTransferForMasterAccount", new(*UniversalTransferResponse)},
		{"sub_account/deposit_assets_into_the_managed_sub_account", "DepositAssetsIntoTheManagedSubAccount", new(struct {
			TransactionID types.PreciseNumber `json:"tranId"`
		})},
		{"sub_account/get_managed_sub_account_deposit_address", "GetManagedSubAccountDepositAddress", new(*ManagedSubAccountDepositAddres)},
		{"sub_account/query_managed_sub_account_asset_details", "GetManagedSubAccountAssetsDetails", new([]*ManagedSubAccountAssetInfo)},
		{"sub_account/query_managed_sub_account_futures_asset_details", "GetManagedSubAccountFutureesAssetDetails", new(*ManagedSubAccountFuturesAssetDetail)},
		{"sub_account/query_managed_sub_account_list", "GetManagedSubAccountList", new(*ManagedSubAccountList)},
		{"sub_account/query_managed_sub_account_margin_asset_details", "GetManagedSubAccountMarginAssetDetails", new(*SubAccountMarginAsset)},
		{"sub_account/query_managed_sub_account_snapshot", "GetManagedSubAccountSnapshot", new(*SubAccountAssetsSnapshot)},
		{"sub_account/query_managed_sub_account_transfer_log_master_account_investor", "GetManagedSubAccountTransferLogForInvestorMasterAccount", new(*SubAccountTransferLog)},
		{"sub_account/query_managed_sub_account_transfer_log_master_account_trading", "GetManagedSubAccountTransferLogForTradingTeam", new(*SubAccountTransferLog)},
		{"sub_account/query_managed_sub_account_transfer_log_sub_account_trading", "GetManagedSubAccountTransferLog", new(*ManagedSubAccountTransferLog)},
		{"sub_account/withdrawl_assets_from_the_managed_sub_account", "WithdrawAssetsFromManagedSubAccount", new(struct { //nolint:misspell // Official SDK operation identifier.
			TransactionID types.PreciseNumber `json:"tranId"`
		})},
		{"vip_loan/get_borrow_interest_rate", "GetVIPBorrowInterestRate", new([]*BorrowInterestRate)},
		{"vip_loan/get_collateral_asset_data", "GetVIPCollateralAssetData", new(*VIPCollateralAssetData)},
		{"vip_loan/get_loanable_assets_data", "GetVIPLoanableAssetsData", new(*VIPLoanableAssetsData)},
		{"vip_loan/get_vip_loan_interest_rate_history", "GetVIPLoanInterestRateHistory", new(*VIPLoanInterestRate)},
		{"vip_loan/query_vip_loan_fixed_rate_market", "GetVIPFixedRateLoanMarket", new(*VIPFixedRateLoanMarket)},
		{"vip_loan/vip_loan_borrow", "VIPLoanBorrow", new(*VIPLoanBorrow)},
		{"vip_loan/vip_loan_fixed_rate_borrow", "BorrowVIPFixedRateLoan", new(*VIPFixedRateBorrow)},
		{"vip_loan/vip_loan_renew", "VIPLoanRenew", new(*LoanRenewResponse)},
		{"vip_loan/vip_loan_repay", "VIPLoanRepay", new(*VIPLoanRepayResponse)},
		{"vip_loan/check_vip_loan_collateral_account", "CheckLockedValueVIPCollateralAccount", new(*LockedValueVIPCollateralAccount)},
		{"vip_loan/get_vip_loan_accrued_interest", "GetVIPLoanAccruedInterest", new(*VIPLoanAccruedInterests)},
		{"vip_loan/get_vip_loan_ongoing_orders", "GetVIPLoanOngoingOrders", new(*VIPLoanOngoingOrders)},
		{"vip_loan/get_vip_loan_repayment_history", "GetVIPLoanRepaymentHistory", new(*VIPLoanRepaymentHistoryResponse)},
		{"vip_loan/query_application_status", "GetVIPApplicationStatus", new(*LoanApplicationStatus)},
		{"wallet/account_api_trading_status", "GetAccountTradingAPIStatus", new(*TradingAPIAccountStatus)},
		{"wallet/account_info", "GetUserAccountInfo", new(*AccountInfo)},
		{"wallet/account_status", "GetAccountStatus", new(struct {
			Data string `json:"data"`
		})},
		{"wallet/daily_account_snapshot", "GetDailyAccountSnapshot", new(*DailyAccountSnapshot)},
		{"wallet/get_api_key_permission", "GetAPIKeyPermission", new(*APIKeyPermissions)},
		{"wallet/asset_dividend_record", "GetAssetDevidendRecords", new(*AssetDividendRecord)},
		{"wallet/dust_convert", "DustConvert", new(*DustConvertResult)},
		{"wallet/dust_convertible_assets", "GetDustConvertibleAssets", new(*DustConvertibleAssets)},
		{"wallet/dust_transfer", "DustTransfer", new(*Dusts)},
		{"wallet/dustlog", "GetDustLog", new(*DustLog)},
		{"wallet/funding_wallet", "GetFundingAssets", new([]*FundingAsset)},
		{"wallet/get_assets_that_can_be_converted_into_bnb", "GetAssetsThatCanBeConvertedIntoBNB", new(*AssetsDust)},
		{"wallet/get_cloud_mining_payment_and_refund_history", "GetCloudMiningPaymentAndRefundHistory", new(*CloudMiningPR)},
		{"wallet/get_open_symbol_list", "GetOpenSymbolList", new([]*OpenSymbolListing)},
		{"wallet/get_spot_asset_tags", "GetSpotAssetTags", new([]*GetSpotAssetTagsResponse)},
		{"wallet/query_user_delegation_history", "GetUserDelegationHistory", new(*UserDelegationHistory)},
		{"wallet/query_user_universal_transfer_history", "GetUserUniversalTransferHistory", new(*UniversalTransferHistory)},
		{"wallet/query_user_wallet_balance", "GetUserWalletBalance", new([]*UserWalletBalance)},
		{"wallet/toggle_bnb_burn_on_spot_trade_and_margin_interest", "ToggleBNBBurn", new(*BNBBurnOnSpotAndMarginInterest)},
		{"wallet/trade_fee", "GetTradeFees", new([]*TradeFee)},
		{"wallet/user_asset", "GetUserAssets", new([]*FundingAsset)},
		{"wallet/user_universal_transfer", "UserUniversalTransfer", new(struct {
			TransferID types.PreciseNumber `json:"tranId"`
		})},
		{"wallet/all_coins_information", "GetAllCoinsInfo", new([]*CoinInfo)},
		{"wallet/deposit_address", "GetDepositAddressForCurrency", new(*DepositAddress)},
		{"wallet/deposit_history", "DepositHistory", new([]*DepositHistory)},
		{"wallet/fetch_deposit_address_list_with_network", "GetDepositAddressListWithNetwork", new([]*DepositAddressAndNetwork)},
		{"wallet/fetch_withdraw_address_list", "GetWithdrawAddressList", new([]*WithdrawAddress)},
		{"wallet/fetch_withdraw_quota", "GetWithdrawQuota", new(*WithdrawQuota)},
		{"wallet/one_click_arrival_deposit_apply", "OneClickArrivalDepositApply", new(*DepositCreditApplyResponse)},
		{"wallet/withdraw", "WithdrawCrypto", new(*WithdrawResponse)},
		{"wallet/withdraw_history", "WithdrawHistory", new([]*WithdrawStatusResponse)},
		{"wallet/get_symbols_delist_schedule_for_spot", "GetSymbolsDelistScheduleForSpot", new([]*DelistSchedule)},
		{"wallet/system_status", "GetSystemStatus", new(*SystemStatus)},
		{"wallet/broker_withdraw", "BrokerTravelRuleWithdraw", new(*BrokerTravelRuleWithdrawResponse)},
		{"wallet/check_questionnaire_requirements", "GetQuestionnaireRequirements", new(*QuestionnaireRequirement)},
		{"wallet/deposit_history_travel_rule", "GetLocalEntitiesDepositHistory", new([]*LocalEntityDepositDetail)},
		{"wallet/deposit_history_v2", "GetTravelRuleDepositHistoryV2", new([]*GetTravelRuleDepositHistoryV2Response)},
		{"wallet/fetch_address_verification_list", "GetAddressVerifications", new([]*GetAddressVerificationsResponse)},
		{"wallet/get_country_list", "GetTravelRuleCountries", new(*GetTravelRuleCountriesResponse)},
		{"wallet/get_region_list", "GetTravelRuleRegions", new(*GetTravelRuleRegionsResponse)},
		{"wallet/submit_deposit_questionnaire", "SubmitBrokerDepositQuestionnaire", new(*SubmitBrokerDepositQuestionnaireResponse)},
		{"wallet/submit_deposit_questionnaire_travel_rule", "SubmitDepositQuestionnaire", new(*QuestionnaireDepositResponse)},
		{"wallet/submit_deposit_questionnaire_v2", "SubmitDepositQuestionnaireV2", new(*SubmitDepositQuestionnaireV2Response)},
		{"wallet/vasp_list", "GetOnboardedVASPList", new([]*VASPItemInfo)},
		{"wallet/withdraw_history_v1", "GetTravelRuleWithdrawalHistory", new([]*GetTravelRuleWithdrawalHistoryResponse)},
		{"wallet/withdraw_history_v2", "WithdrawalHistory", new([]*LocalEntityWithdrawalDetail)},
		{"wallet/withdraw_travel_rule", "TravelRuleWithdraw", new(*TravelRuleWithdrawResponse)},
	} {
		t.Run(tc.name, func(t *testing.T) {
			fixture, ok := fixtures[tc.fixture]
			require.True(t, ok, "documented fixture must exist")
			current.Store(fixture)
			require.NoError(t, local.SendAuthHTTPRequest(t.Context(), exchange.RestSpot, fixture.Method, fixture.Path, nil, request.UnAuth, nil, tc.response), "documented response must decode through the mock transport")
			assertResponseFields(t, fixture.Data, reflect.TypeOf(tc.response), tc.name)
		})
	}
}
