name: misc
on: [push, pull_request]
jobs:
  misc:
    name: miscellaneous checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.x
      - name: Run misc checks script
        run: bash scripts/misc_checks.sh
    

