name: codespell
on:
  push:
    branches: [master]
  pull_request:
  merge_group:
permissions:
  contents: read
jobs:
  codespell:
    name: Spell checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: codespell-project/actions-codespell@master
        with:
          args: --dictionary=-,./contrib/spellcheck/codespell_custom_dictionary.txt
